Added more logic to scan flows

diff --git a/.github/actions/performFlowsAnalysis/action.yml b/.github/actions/performFlowsAnalysis/action.yml
--- a/.github/actions/performFlowsAnalysis/action.yml
+++ b/.github/actions/performFlowsAnalysis/action.yml
@@ -2,9 +2,19 @@ name: "Perform Flows Analysis"
 
 inputs:
   pathToScan:
-    description: "Path to a directory with flows to scan"
+    description: "Path to a directory to scan"
     type: string
     default: "force-app"
+
+  failureThresholdLevel:
+    description: "Failure threshold level"
+    type: choice
+    default: "never"
+    options:
+      - "error"
+      - "warning"
+      - "note"
+      - "never"
 
   failWhenViolations:
     description: "Fail if violations threshold is exceeded"
@@ -15,6 +25,11 @@ inputs:
     description: "Violations threshold"
     type: number
     default: 15
+
+  reportFileName:
+    description: "Name of a report file containing flows scan results"
+    type: string
+    default: "salesforce-flows-analyzer-results"
 
 runs:
   using: "composite"
@@ -38,14 +53,47 @@ runs:
       continue-on-error: true
       env:
         PATH_TO_SCAN: ${{ inputs.pathToScan }}
+        FAILURE_THRESHOLD_LEVEL: ${{ inputs.failureThresholdLevel }}
+        REPORT_FILE_NAME: ${{ inputs.reportFileName }}
       run: |
         echo "⏳ Running 'lightning-flow-scanner' against '$PATH_TO_SCAN' path"
 
-        sf flow scan --directory="$PATH_TO_SCAN"
+        # temporary disabling immediate exit by using "set +e/-e" commands (i.e. some kind of try/catch)
+        set +e
+
+        sf flow scan \
+            --directory="$PATH_TO_SCAN" \
+            --failon="$FAILURE_THRESHOLD_LEVEL" \
+            > "${REPORT_FILE_NAME}.txt"
+
+        # capturing the exit status of the 'sf flow scan' command
+        SCAN_RESULT_STATUS_CODE=$?
+
+        set -e
 
         echo "✅ Execution of 'lightning-flow-scanner' is successfully completed"
 
+        # setting scan results into variables
+        echo "SCAN_RESULT_STATUS_CODE=$SCAN_RESULT_STATUS_CODE" >> $GITHUB_ENV
+
+        # TEST: list files
+        ls -l
+
     - name: "Check Analysis Results"
       shell: bash
+      env:
+        FAILURE_MODE_ENABLED: ${{ inputs.failWhenViolations }}
+        PATH_TO_SCAN: ${{ inputs.pathToScan }}
+        FAILURE_THRESHOLD_LEVEL: ${{ inputs.failureThresholdLevel }}
       run: |
-        echo "Some analysis results..."
+        echo "Failure mode enabled: $FAILURE_MODE_ENABLED"
+        echo "Defined path to scan: $PATH_TO_SCAN"
+        echo "Defined failure threshold level: $FAILURE_THRESHOLD_LEVEL"
+        echo "Analyzer exit code: $SCAN_RESULT_STATUS_CODE"
+
+        if [[ "$FAILURE_MODE_ENABLED" == "true" && SCAN_RESULT_STATUS_CODE -gt 0 ]] ; then
+
+          echo "❌ Failing the step execution due to reported code analysis violations."
+          exit 1
+
+        fi
