Returned back main logic

diff --git a/.github/actions/performCodeAnalysis/action.yml b/.github/actions/performCodeAnalysis/action.yml
--- a/.github/actions/performCodeAnalysis/action.yml
+++ b/.github/actions/performCodeAnalysis/action.yml
@@ -39,3 +39,39 @@ runs:
       if: ${{ inputs.failWhenViolations == 'true' }}
       run: |
         echo "✅ TEST SINGLE STEP IS EXECUTED"
+
+    - name: "Install Plugin - Salesforce Code Analyzer"
+      continue-on-error: false
+      shell: bash
+      env:
+        PLUGIN_VERSION: "latest"
+      run: |
+        echo ">>> DEBUG: 'failWhenViolations' = ${{ inputs.failWhenViolations }}"
+
+        echo "⏳ Installing 'sfdx-scanner' plugin if no originally installed version is available..."
+
+        (sf plugins | grep -i "sfdx-scanner") || (echo "y" | sf plugins install @salesforce/sfdx-scanner@$PLUGIN_VERSION)
+
+        echo "✅ 'sfdx-scanner' plugin is installed successfully"
+
+    - name: "Run Salesforce Code Analyzer"
+      id: runCodeAnalyzer
+      uses: forcedotcom/run-code-analyzer@v1
+      with:
+        run-command: run
+        run-arguments: --normalize-severity --target . --outfile results.html
+        results-artifact-name: salesforce-code-analyzer-results
+
+    - name: "Check Analysis Results"
+      shell: bash
+      if: |
+        inputs.failWhenViolations == 'true' &&
+        steps.runCodeAnalyzer.outputs.exit-code > 0 ||
+        steps.runCodeAnalyzer.outputs.num-sev1-violations > 0 ||
+        steps.runCodeAnalyzer.outputs.num-violations > 15
+      run: |
+        echo "Reported violations: ${{ steps.runCodeAnalyzer.outputs.num-violations }}"
+        echo "Defined threshold: ${{ inputs.violationsThreshold }}"
+
+        echo "❌ Violations threshold is exceeded. Failing the step execution."
+        exit 1
