Added informative text when failing due to validation threshold exceeding

diff --git a/.github/actions/performCodeAnalysis/action.yml b/.github/actions/performCodeAnalysis/action.yml
--- a/.github/actions/performCodeAnalysis/action.yml
+++ b/.github/actions/performCodeAnalysis/action.yml
@@ -36,5 +36,7 @@ runs:
         inputs.failWhenViolations == true &&
         steps.runCodeAnalyzer.outputs.exit-code > 0 ||
         steps.runCodeAnalyzer.outputs.num-sev1-violations > 0 ||
-        steps.runCodeAnalyzer.outputs.num-violations > 20
-      run: exit 1
+        steps.runCodeAnalyzer.outputs.num-violations > 2
+      run: |
+        echo "❌ Violations threshold is exceeded. Failing the step execution."
+        exit 1
